### ISSUE TITLE
Time should be precise

### ISSUE THREAD

**Issue by skyminert** [DXgovernance/davi-monorepo#103]
Instead of a proposal saying "1 day left" it should say exactly how much time is left.  Why doesn't it?

Was this a design choice?

![image](https://user-images.githubusercontent.com/57817726/213524614-6c5f21ae-82f7-4b23-b42a-4768b70aac96.png)

**Comment by rossneilson** [comment]
We can add more detail once its under 1 day

**Comment by skyminert** [comment]
better to have exact the whole time.  Don't care about the time just under one day.  I want to know if it's 23 hrs or 47 hrs.

**Comment by dcrescimbeni** [comment]
Maybe we could have both?

I think it's useful to have a ballpark around remaining time

**Comment by rossneilson** [comment]
We have the exact time under proposal history, maybe we could expand that by default or make it more obvious
@borisblock3007 thoughts?

**Comment by skyminert** [comment]
![image](https://user-images.githubusercontent.com/57817726/213526381-90ff5fed-9e03-452f-b5a8-6f129e0403bc.png)

**Comment by skyminert** [comment]
I see here now.  when is 9:11am?

**Comment by skyminert** [comment]
that's why how many days, hours, mins is so important

**Comment by skyminert** [comment]
Just to summarize, we know from 3 years of governance in Alchemy and DXvote that exact times amounts matter a lot.  
So we should design based off of what we already know.  

If any questions about these things, you can ask one of the power users

**Comment by rossneilson** [comment]
Solution always show the current time remaining plus the next smallest unit of measurement.
But with the exception of seconds until we get < 1 minute

Current: "2 hours"
New: "2 hours 10 mins"
examples: "2 weeks 3 days", "3 days. 4 hours", "10 mins"
