### ISSUE TITLE
Subgraph Fetcher - Active Proposal IDs

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#121]
This task aims to create a version of our hook which uses a subgraph fetcher instead of RPCs and should be used by default. 

RPC hook to target `useGetActiveProposals`
This is one which we could technically do a lot more efficiently by just directly fetching proposals instead of proposal IDs in the subgraph but since it would require a big redesign of how we render proposal lists we will do it later as an optimisation.

Testing should ensure behaviour is exactly the same as the RPC hook.

The interface and types should be the same but can be altered to be more of a middle ground. Changes can also be made to the subgraph schema if required.

Refer to the subgraph setup PR for reference

**Comment by rossneilson** [comment]
Updated description with correct hook title

**Comment by Kenny-Gin1** [comment]
So apparently, the hook `useGetActiveProposals` only gets back the number of active proposals in the guild, not the actual proposal ids. I'll finish up the subgraph implementation for this one, though, and move on to the one that fetches active proposal IDs though. But FYI! @rossneilson
