### ISSUE TITLE
Subgraph & RPC Fetcher - Proposal

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#123]
This task aims to create a version of our hook which uses a subgraph fetcher instead of RPCs and should be used by default. 

RPC hook to target `useProposal`, `useProposalVotes`, `useProposalCalls`
We should just be exposing one useProposal hook for consumption by the components since its nested data. This makes even more sense with the subgraph as we can fetch all the data in one query. This will require some changes to the RPC fetcher also.
**We also need to add snapshot data to our REP guild schema on the subgraph in this issue**

Testing should ensure behaviour is exactly the same as the RPC hook.

The interface and types should be the same but can be altered to be more of a middle ground. Changes can also be made to the subgraph schema if required.

Refer to the subgraph setup PR for reference

**Comment by Kenny-Gin1** [comment]
@rossneilson What do you mean by "we also need to add snapshot data to our REP guild schema"? Would it also be possible to add a snapshot of the UI and/or acceptance criteria so I know that my changes are OK?

**Comment by rossneilson** [comment]
> @rossneilson What do you mean by "we also need to add snapshot data to our REP guild schema"? Would it also be possible to add a snapshot of the UI and/or acceptance criteria so I know that my changes are OK?


In the subgraph currently we dont track snapshot IDs in proposals, we need to add this to the schema and mappings in order for the UI to work.

Acceptance criteria should just be exactly the same data where any proposal data hooks are consumed, so you can compare with production, develop or by swapping out your new subgraph features with the old RPC ones, behaviour should be identical.

**Comment by dcrescimbeni** [comment]
@mprasanjith I was thinking of tackling this issue.

Will it be affected by the refactor you talked about today and thus wait for that to be finished, or can I start with this?

**Comment by mprasanjith** [comment]
No, this one should be fine. I was going to work on this one and didn't realize there's an issue for it. But you can pick this one as I haven't started working on this yet.

**Comment by dcrescimbeni** [comment]
> @dcrescimbeni No, this one should be fine. I was going to work on this one and didn't realize there's an issue for it. But you can pick this one as I haven't started working on this yet.

Cool! If you feel like it, go for it. If not, I'll take a look at it on Monday

**Comment by dcrescimbeni** [comment]
We currently aren't using the `useProposalVotes`. Just to clarify: the idea is to also return (when available) the votes of each address?

This will be related to this PR:
https://github.com/DXgovernance/davi-monorepo/pull/140

**Comment by rossneilson** [comment]
> We currently aren't using the `useProposalVotes`. Just to clarify: the idea is to also return (when available) the votes of each address?
> 
> This will be related to this PR: #140

Yeah, the idea is to as much as possible combine everything under the proposal schema to one hook since that's how we return it from the subgraph (of course RPC version will be getting data from multiple child hooks)
