### ISSUE TITLE
Add Error message when creating proposal or any transaction without wallet

### ISSUE THREAD

**Issue by rulfo71** [DXgovernance/davi-monorepo#125]
**User Story**
As a user, I want to get a descriptive error when creating a proposal without the wallet connected.

**Alternative Solutions**
When creating a proposal, validate the user has the wallet connected. In case it's not connected, show an error message explaining. 

**Additional context**
When creating a proposal without the wallet connected we are getting a modal saying "Transaction Failed" without any description. This is because we don't get useful messages from ethers. To avoid this, we can validate if the wallet is connected before creating the proposal.

**Comment by rossneilson** [comment]
We see this also with voting or basically any transaction, we should add checks there also that prompts a wallet connection
