### ISSUE TITLE
some Guild names missing and then white screen

### ISSUE THREAD

**Issue by skyminert** [DXgovernance/davi-monorepo#133]
some Guild names missing

![image](https://user-images.githubusercontent.com/57817726/214103228-6cd5a4a1-260e-44b9-a426-e74fdfdf52a0.png)

happens often
then when i click on one, get full white screen
https://app.projectdavi.eth.limo/#/gnosis
https://qa.projectdavi.eth.limo/#/gnosis/0x3f842726188FcD932d43bcA291be28138228e6D9
same in qa

**Comment by rossneilson** [comment]
Should be fixed in v3 let us know if you see it again
(sometimes they appear blank for a moment as they load but you shouldn't get white screens and they will eventually appear again)
