### ISSUE TITLE
Changes made on LOCAL env are visible on PROD env

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/davi-monorepo#137]
**Description**
I've left I a comment on my `Discussion` page on Local env and it was visible on PROD env.  

https://app.projectdavi.eth.limo/#/gnosis/0x3f842726188FcD932d43bcA291be28138228e6D9/discussion/kjzl6cwe1jw14b3k807xo4cexyqq5qklv3h3jqqul5rmc366hyz0ddzfpte0alz

**Steps to Reproduce**
1. Spin up localhost
2. Go to DXgov Guild
3. Go to "Filip Vidakovic(Philipp16) Worker Proposal" discussion
4. Scroll to Discussion section
5. See the comment and the like (like was added on PROD env)

**Expected behavior**
Changes made on Localhost should not be visible on PROD env

**Screenshots**

LOCALHOST
![localenv](https://user-images.githubusercontent.com/37701286/214551291-e962eeb1-5d04-477b-b9fa-404901e7037c.jpg)

PROD
![prodenv](https://user-images.githubusercontent.com/37701286/214551312-8375dea0-1631-4d9b-ae20-cf5a5220a97f.jpg)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Ventura v13.1

**Additional context**
Noticed this behavior before, not sure if it's cache but I tried hard-refresh as well. Comment left on Localhost appeared instantly on PROD env

**Comment by rossneilson** [comment]
This is correct behaviour since you are on a production network
