### ISSUE TITLE
Missing content when internet connection is a bit slower

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/davi-monorepo#138]
**Description**
Error when I have poor internet connection, I'm not sure how to reproduce. I've attached couple of screenshots, getting some CORS erros in the console. 

Proposal page > after hard refresh everything is still the same

**Steps to Reproduce**
1. Go to PROD or QA testing env
2. Navigate to different pages
3. Notice some content not showing 

**Expected behavior**
Content should be visible right away

**Screenshots**
Occasionally getting this error:
![error-on-fe](https://user-images.githubusercontent.com/37701286/214561718-dfca5076-88f6-426c-81bd-8d16fc4a8439.jpg)

Some Guild names are missing:
![missing-guild-names](https://user-images.githubusercontent.com/37701286/214561735-cf38e291-1fa4-4cb4-8c4a-8dcaa40a7149.jpg)

On Proposal page Description is not visible and `For` voting option is not visible. Same on Dino's proposal e.g. (hard-refresh not helping)
![missing-info](https://user-images.githubusercontent.com/37701286/214561771-9636adce-2f74-4d52-aecd-c85a6d79f4c9.jpg)
![dino-proposal](https://user-images.githubusercontent.com/37701286/214561789-d5d7162f-fc68-47fd-aee9-d233aa1499f5.jpg)

Occassionally entire Guilds content is missing, until I refresh:
![missing-content](https://user-images.githubusercontent.com/37701286/214561816-5a080917-4436-49a9-88ee-5248b84fa795.jpg)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Ventura v13.1

**Additional context**

**Comment by rossneilson** [comment]
We should investigate this again once we have all new RPC fetchers implemented to see if it persists in the new architecture.

**Comment by rossneilson** [comment]
The two screenshots on proposal page are related to ipfs / orbis so can be ignored for now. Main issues here is data (guilds and guild names) not appearing as this means data is not being fetched.

**Comment by rossneilson** [comment]
Slowing down my internet didnt replicate these so going to close this in favour of more detailed breakdowns in recent bug reports
