### ISSUE TITLE
Support both html and md and unify to md

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#145]
We encountered a bug where our html broke the previous markdown-to-jsx library we used which supported both markdown and HTML (just obviously not handling HTML very well)
So we moved to just a HTML parser but then found out we actually use both md and HTML in discussions and proposals respectively. Very bad.

So we now need to backwards compatibly support both meaning we have to check for HTML and render appropriately.
https://www.npmjs.com/package/is-html

We should also move to only using markdown for both proposals and discussions. This is safer and more compatible with other applications like viewing posts directly in obris.

**Comment by rossneilson** [comment]
Fix in old DAVI repo so we can hotfix unde v2.4.2 branched from 2.4.1 then replicate into monorepo

**Comment by rossneilson** [comment]
https://github.com/DXgovernance/davi-monorepo/pull/146

**Comment by mprasanjith** [comment]
Fixed in #177.
