### ISSUE TITLE
Permissions page & Subgraph hook

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#15]
All of our governance systems use the same permissions contract meaning that we can easily make a UI for all DAOs in DAVI. 

Permissions consist of:
- Assets 
- Generic calls

The assets tab shows what assets the DAO can approve and transfer around (e.g: DAO x can transfer 1000 DAI per proposal and infinite DXD per proposal but has no other permissions set so cannot transfer USDC at all).

Generic calls shows all contracts and their functions which can be called.

This UI will likely work best as a table as we need to show multiple rows of permissions for a DAO. Likely it doesn't need to be anything incredibly intuitive as it is already a power user screen.

**Comment by dcrescimbeni** [comment]
@rossneilson  What does the "advanced view" toggle does?

**Comment by rossneilson** [comment]
> @rossneilson What does the "advanced view" toggle does?

Advanced is supposed to show direct addresses and function sigs instead of our rich contract titles and function titles etc

**Comment by rossneilson** [comment]
Boris added a prototype 
https://www.figma.com/proto/EttR9KZTQUrirqMDmI3fQv/DAVI-Dapp-Draft?page-id=355%3A11084&node-id=544%3A9144&viewport=1146%2C-707%2C0.22&scaling=min-zoom&starting-point-node-id=360%3A11110
