### ISSUE TITLE
DEV env - Transaction reverted error on FE and Console

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/davi-monorepo#168]
**Description**
Noticed this error multiple times, it just break for some reason when on any Guild page. But I’ve noticed same behaviour it across the App on any page, screenshot 1.

Screenshot 2 - getting this error in console all the time. On page refresh, on Landing page, Guild page, Proposal page

**Steps to Reproduce**
1. Spin up local env with `pnpm davi:dev`
2. Navigate to any Guild or just try using the App

**Expected behavior**
App should not break randomly

**Screenshots**
<img width="1432" alt="dev-transaction-reverted-error" src="https://user-images.githubusercontent.com/37701286/217222409-3716a12b-e32d-406b-80ec-c18e6851b34e.png">

<img width="1440" alt="development-env-gnosis-contract-reverted" src="https://user-images.githubusercontent.com/37701286/217218093-bddfccf6-d5d0-4d70-b085-df6d79f2c795.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Ventura v13.1

**Comment by Filipv95** [comment]
Adding additional Image on Guilds page
<img width="1430" alt="development-env-gnosis" src="https://user-images.githubusercontent.com/37701286/217223116-35f0f7ba-e4c8-4b9b-ac6f-a3a8bc3161fd.png">

**Comment by rossneilson** [comment]
Should be fixed in v3
reopen if found again
