### ISSUE TITLE
Gov 1.5 - Scheme selection page

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#17]
With DXdao contracts, nicknamed "Gov 1.5" due to it being only one large change away from "Gov 2.0" we have a more complex system.
The same as in DXdao currently this architecture has schemes. Schemes are like sub parts of a DAO with their own permissions and funds.
Before making a proposal a user has to select which scheme they want to use and we need to make this a smooth experience. 

We have a list of schemes and each scheme has the following data:
- Can the scheme use root DAO funds? (This basically gives them access to all the money in the main DAO)
- If no to the above, then the scheme has it's own funds that need shown to the user
- Permissions, what the scheme is allowed to do (what contracts it can call / assets it can transfer)

My thoughts on this design is that it should be a page before the current proposal creation page right now.
Then the user will see two windows, one to select the scheme from a list and the next pane to show the details of what the scheme can do and it's funds.
Then once they press next they go to the usual creation page.

We also need to consider how we will show which scheme a proposal is using once it has been made.

**Comment by borisblock3007** [comment]
This is the latest draft for the schemes page. I think it might work, would appreciate some feedback :)

![Image](https://user-images.githubusercontent.com/25454493/219363794-e48f9e20-eefc-45f8-8aa9-33b13c154fa9.png)

**Comment by rossneilson** [comment]
> This is the latest draft for the schemes page. I think it might work, would appreciate some feedback :)
> 
> ![Image](https://user-images.githubusercontent.com/25454493/219363794-e48f9e20-eefc-45f8-8aa9-33b13c154fa9.png)
> 
> 

Looks great!

@AugustoL you want a look at this?

**Comment by rossneilson** [comment]
Newest draft here: https://www.figma.com/file/Z2yCtX1NLhdJYYoBiXkdMg/DAVI-v1?node-id=1%3A24032&t=fwxnisVmWeBZ2ISh-1

Ready for implementation

**Comment by rossneilson** [comment]
If we use a 1.5 DAO then we should show this page when the user clicks create proposal, then we:
- List all schemes
- Show scheme parameters (might need to add a getter to contracts, talk to @fnanni-0 or @MiltonTulli and look in controller, voting machine and schemes)
- Show permissions for scheme address
- Show treasury for scheme address

Once selected we pass the scheme address in the URL to the normal create proposal page which then basically overrides the dao id.

**Comment by dcrescimbeni** [comment]
Which design is the final one? I'm seeing 4 variations in figma.

@rossneilson @borisblock3007

**Comment by rossneilson** [comment]
> Which design is the final one? I'm seeing 4 variations in figma.
> 
> @rossneilson @borisblock3007

One furthest to the right, but maybe we could make that clearer in future @borisblock3007 highlighting final designs

**Comment by dcrescimbeni** [comment]
I have some questions about the implementation:

Should we show what scheme is selected on the Proposal page? 

Should we add a button to go back to the scheme selection on the Proposal page?


Since we're not enforcing unique scheme names, should we add extra data to differentiate them?


![Image](https://user-images.githubusercontent.com/75996796/224702165-87878358-5ff5-4f69-b0fa-eb79fd33c85b.png)


What goes in the scheme selection text? (screenshot from Figma)


![Image](https://user-images.githubusercontent.com/75996796/224702349-c3bfa999-ff31-4e4c-8948-07c288f9c85a.png)

@rossneilson @borisblock3007

**Comment by dcrescimbeni** [comment]
Also, this is a screenshot of the current state of the scheme selection page:


![Image](https://user-images.githubusercontent.com/75996796/224705154-4b86db42-135d-4df1-973e-04c153234d82.png)

**Comment by rossneilson** [comment]
> Should we show what scheme is selected on the Proposal page?

Yes, lets make it something simple for now and @borisblock3007 could we get a design for where it should go longer term 

> Should we add a button to go back to the scheme selection on the Proposal page?

Yeah, can just be a normal back button

> Since we're not enforcing unique scheme names, should we add extra data to differentiate them?

I think now we don't have a metadata field on the contracts right, so not sure what we can do right now for that

> What goes in the scheme selection text? (screenshot from Figma)

For now just leave it blank, unless we have a metadata field which I think we dont
