### ISSUE TITLE
DEV env - Landing page loader seems broken

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/davi-monorepo#170]
**Description**
This issue is noticable on Landing page. On `Gnosis` and `Goerli` networks it seems to take more time to load and it is very visible.
On `Ethereum` network the page load faster so it's not that bad, but you can still see the bug for short moment.

**Steps to Reproduce**
1. Spin up local env with `pnpm davi:dev`
2. Refresh Landing page

**Expected behavior**
Should refresh with no issues

**Screenshots**
<img width="1435" alt="dev-gnosis-loader" src="https://user-images.githubusercontent.com/37701286/217227209-f8dd1b37-2554-4c3a-980f-a349a22858aa.png">

<img width="1435" alt="goerli-network-development" src="https://user-images.githubusercontent.com/37701286/217227257-ec850754-87b9-4070-9489-b05a5f771fd1.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Ventura v13.1

**Comment by rossneilson** [comment]
Should be fixed in v3
