### ISSUE TITLE
DEV env - data loading issues

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/davi-monorepo#171]
**Description**
Happens that `Guild names` do not load on `Landing` page.
On `Governance` and `All Proposal` page, `Guild name` and option percentage are not showing. Sometimes happens that all the data is visible when the page loads, but after couple of seconds it disappears (looks like it is loading).

**Steps to Reproduce**
1. Spin up local env with `pnpm davi:dev`
2. Visit all Guilds and check if data is being loaded correctly

**Expected behavior**
All data should be visible when the page loads

**Screenshots**
<img width="1433" alt="dev-guild-names" src="https://user-images.githubusercontent.com/37701286/217229157-9bec6785-0883-4be4-8e83-3c9953806f27.png">

<img width="1436" alt="dev-missing-data" src="https://user-images.githubusercontent.com/37701286/217229188-783710b3-fe58-4af4-85fd-379b9f21b61e.png">

<img width="1436" alt="dev-swapr-guild" src="https://user-images.githubusercontent.com/37701286/217229221-0257ebae-2991-41a5-b900-eec0ae874903.png">

<img width="1439" alt="dev-governance-page" src="https://user-images.githubusercontent.com/37701286/217229583-926c0d2d-9134-4cec-aec2-b4195cdb3420.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Ventura v13.1

**Additional information**
Same behavior is noticable for every Guild.

**Comment by rossneilson** [comment]
Should be fixed in v3
