### ISSUE TITLE
Execute Proposal did not prompt wallet transaction in Frame

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/davi-monorepo#185]
https://app.projectdavi.eth.limo/#/gnosis/0x27738372381c69baEE8efd832eFA097295418b1B/proposal/0x35e105a383fda3769d16231fbc3de78e0510f47ce5c33f7d6f67e70b86211098 

I tried to execute this proposal on Chrome with my Frame wallet and it was stuck on this screen:
<img width="1307" alt="Screenshot 2023-02-09 at 9 02 38 AM" src="https://user-images.githubusercontent.com/47428627/217849967-cbc5fed8-77bf-4ed9-a9e9-4ed72438245a.png">

I moved to firefox and metamask and i was able to execute the proposal no problem.

**Comment by rossneilson** [comment]
Looking into it, seems to be RPC related when estimating gas

**Comment by rossneilson** [comment]
Should be fixed in v3
