### ISSUE TITLE
Update subgraph to new dxdao-contracts v2

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#188]
We built the current subgraph for gov 1.5 wit what was in develop but they underwent a major refactor after the first audit report and so we need to update the subgraph to work with them. 

Augusto will be the best reference for this as most changes were done by him. 

Might be a good mobbing task. 

Most up to date code: https://github.com/DXgovernance/dxdao-contracts/pull/300
Better documented PR missing the changes from above PR: https://github.com/DXgovernance/dxdao-contracts/pull/277

I honestly don't know the required changes in here as it's pretty huge but Augusto says most of the changes are internal to the contracts.  Hopefully it doesn't take too long to get all the mappings and schemas working as before in this new version. The audit is not entirely complete but there shouldn't be any more major changes. 

Apologies for lack of detail, a lot of research work involved here. 

This will unblock integration of Gov 1.5 in DAVI.

**Comment by dcrescimbeni** [comment]
About this, the subgraph for the 1.5 contracts isn't merged in the current monorepo. I guess that would take some time on its own.

Should we first add the code to the monorepo? Or work on the subgraph-1-5 repo and then merge it?

**Comment by Kenny-Gin1** [comment]
Want to know this as well!

**Comment by rossneilson** [comment]
Oh its not! yes we should do that also, everything to the monorepo

**Comment by Kenny-Gin1** [comment]
This ticket is done... kind of. But there seem to have appeared other issues in the monorepo when merging the 1.5 stuff. We synced with @MiltonTulli and think it's best to do this together with the #192 ticket.

**Comment by Filipv95** [comment]
@rossneilson not sure how to test this, would `regression` test be enough i.e. everything should work as expected?

**Comment by Filipv95** [comment]
Checked `Gnosis` and `Ethereum` networks and looks good to me!

`Localhost` network not working, guessing it's something with config
