### ISSUE TITLE
Gov 1.5 Fetchers - Sidebar (configs&members)

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#191]
Pulling together a couple of hooks here that should support one part of DAVI with our new 1.5 governance system.

If you start by looking in Pages/Guilds/Guilds.tsx this is the page we want to be able to see after this issue but focused on the `GuildSidebarWrapper`. This means adding hooks inside that wrapper in our new store:

    `hooks: {
      writers: { useWithdrawTokens }, (This can be null since 1.5 is REP style)
      fetchers: {
        useTotalLocked,
        useVotingPowerOf,
        useVoterLockTimestamp, (Also null)
        useMemberCount,
        useGuildConfig,
      },
    },`

These should all be subgraph fetchers matching the same interface and typing of the guild fetchers we already have. This will maybe require a bit of data manipulation and if something doesn't make sense we can modify the typings to something in the middle. Just ensure guild fetcher work correctly still. 

Acceptance criteria:
When clicking on a localhost 1.5 guild we should be able to see the guild sidebar of the main guild page. None of the page content of the DAO should be shown, perhaps we need to mock return null data to not break things in our new store.

**Comment by rulfo71** [comment]
@rossneilson these should all be subgraph fetchers? 
i'm looking at it and for the current implementations like `SnapshotERC20Guild` and `SnapshotRepERC20Guild` we are doing  `useTotalLocked` and `useVotingPowerOf` through RPCs. For governance 1.5 will be the same, right? or are we going to get those from subgraph?   

For the others, `useMemberCount` and `useGuildConfig` yes i think we can get them from subgraph.
