### ISSUE TITLE
Guild subgraph - votingPercentageForProposalExecution

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#204]
Currently it seems we are storing votingPowerForProposalExecution in our guild config handler. Instead we should be storing votingPercentageForProposalExecution as this doesn't change based on total supply. 

To test we can check quorum on guilds. Currently in gnosis chain we see 0% for DXgov guild when it should be 40%
![Screenshot 2023-02-14 at 15 15 44](https://user-images.githubusercontent.com/39137239/218654768-52feebe0-3955-4383-9938-30a1f47bb29f.jpg)

**Comment by Kenny-Gin1** [comment]
This was one of the bugs that we looked at in: https://github.com/DXgovernance/davi-monorepo/pull/200 and should therefore be solved there. I'll move it to track the issue!
