### ISSUE TITLE
Automation - run Smoke test on different envs

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/davi-monorepo#206]
Should improve the way of running the Smoke test, added commands for running the `Smoke test` on different env (local, QA, PROD).
These commands will be used in future for all tests.

Also should add `README.md` file, which will contain required explanations/info for someone to run the test.

**Comment by rossneilson** [comment]
When we say different environments do we mean on different networks?
If not don't we just run smoke tests on different branches for QA and prod?

**Comment by Filipv95** [comment]
The PR regarding this issue
https://github.com/DXgovernance/davi-monorepo/pull/218
