### ISSUE TITLE
Vote bars don't show if nobody voted

### ISSUE THREAD

**Issue by dcrescimbeni** [DXgovernance/davi-monorepo#242]
**Description**
The vote progress bar doesn't show for proposals with no votes, but the checkered flag does.

![image](https://user-images.githubusercontent.com/75996796/221831348-7c43fa8b-3c27-495a-a801-68b643302538.png)

**Steps to Reproduce**
Either go to a proposal with no votes or create a new proposal.

**Expected behavior**
Regardless of whether there are votes, I'd expect to see the bars.

**Comment by rulfo71** [comment]
i'm not being able to reproduce this bug. 
On a proposal with 0 votes i'm getting this: 
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/5303411/222135635-477a2db5-d934-4403-b6cb-960b6526bba9.png">

I also tried hardcoding a very low vote value (0,0001%) and also worked well. 
@Filipv95 maybe you can try to reproduce it ?

**Comment by rulfo71** [comment]
same: 
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/5303411/222137073-fca142e5-0daa-4e5a-8581-78b1e0222017.png">
