### ISSUE TITLE
Creating wxdai transfer crashes page

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#267]
![Screenshot 2023-03-06 at 18 56 14](https://user-images.githubusercontent.com/39137239/223077071-35fc0f40-43c2-4863-abaa-966b066e49c3.jpg)

![Screenshot 2023-03-06 at 18 56 32](https://user-images.githubusercontent.com/39137239/223077160-248df2af-ae0d-4525-82b8-a3da2ba1230d.jpg)

**Comment by rulfo71** [comment]
maybe this is related to #256 ? 
I haven't tried it but looks similar, may be fixed by @dcrescimbeni 's #257

**Comment by rossneilson** [comment]
> maybe this is related to #256 ? I haven't tried it but looks similar, may be fixed by @dcrescimbeni 's #257

Looks like this still exists in Dino's PR
