### ISSUE TITLE
Broken set config action

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#278]
It seems we arent reading the correct values for the set config action when using the subgraph. This should be an easy fix as we read things like quorum correctly elsewhere.

V3.0.0 (using RPC)
![Screenshot 2023-03-09 at 17 04 28](https://user-images.githubusercontent.com/39137239/223958937-6e2b4398-58f6-440a-8b64-cf7c4e533346.jpg)

V3.1.0 (using subgraph)
![Screenshot 2023-03-09 at 17 06 11](https://user-images.githubusercontent.com/39137239/223959310-78ba3a0f-f9fc-46b5-932d-d16e23c802a8.jpg)

**Comment by 0xvangrim** [comment]
Hey @rossneilson! Are you still able to create this bug? When I tried to set configs, I got the following: 

![Image](https://user-images.githubusercontent.com/59825171/225195713-a168055c-8f19-4a83-8013-37c2509e17be.png)


Which seems to be the same as Subgraph v.3.0.0

**Comment by 0xvangrim** [comment]
Same result on Gnosis. 

![Image](https://user-images.githubusercontent.com/59825171/225195997-d6356a06-8e4c-4c30-a88d-608f0df6d08e.png)

**Comment by rossneilson** [comment]
Oh awesome, definitely still seeing it in production but I guess its fixed in develop, closing.
Thanks for investigating @Kenny-Gin1
