### ISSUE TITLE
App crashes when saving reputation minting action

### ISSUE THREAD

**Issue by yathindrak** [DXgovernance/davi-monorepo#312]
**Description**

The app crashes when saving reputation minting action.

**Steps to Reproduce**

1. Go to create proposal page.
2. Click on `Add Action` button.
3. Select mint reputation.
4. Enter valid values and save the action.

**Expected behavior**

The action should be saved and should be visible in the action builder UI.

**Screenshots**

https://user-images.githubusercontent.com/32919513/225347048-2ab6760d-55da-48c5-b938-4cc3b6c7caec.mov

**Device Information**

- OS: MacOS
- Browser Arc (Chromium)
- Device: [e.g. PC or mobile phone version]

**Additional context**

**Comment by rossneilson** [comment]
This is develop right? seems production is fine
