### ISSUE TITLE
Vote detail not showing

### ISSUE THREAD

**Issue by dcrescimbeni** [DXgovernance/davi-monorepo#317]
**Description**
Voting details (who voted and the voting power) are not shown on the Proposal page.

EDIT: this issue is currently on the `develop` branch, not on prod.

**Steps to Reproduce**

1. Go to a proposal page in a subgraph-supported chain (Gnosis)
2. On the left, a vote detail should be shown, but it's not

**Expected behavior**
Voting detail should be shown on subgraph-supported networks

**Screenshots**
![image](https://user-images.githubusercontent.com/75996796/225921892-b2f95988-f77c-4949-80cc-b9a1a02ce95c.png)

**Comment by rossneilson** [comment]
Is it possible this fell back to rpc?

**Comment by dcrescimbeni** [comment]
> Is it possible this fell back to rpc?

Indeed, I can't see any subgraph-related info. This is on Gnosis:

![image](https://user-images.githubusercontent.com/75996796/226328562-6a689155-8302-4339-9e55-1be27834502e.png)

![image](https://user-images.githubusercontent.com/75996796/226328594-d991ed04-c8f5-4c06-a46b-d7418712af2f.png)

**Comment by rossneilson** [comment]
Closing then as this is expected behaviour, @borisblock3007 maybe we could consider a design for a warning message somewhere in the app if we are on RPC data? Something minimal and not in the way

**Comment by dcrescimbeni** [comment]
Sorry, I wasn't clear in the issue.

In prod, the subgraph info is showing, so this is a config issue somewhere in DAVI that is affecting the develop branch.

This is a screenshot of a proposal on prod

![image](https://user-images.githubusercontent.com/75996796/226330107-73a1be80-3c91-498c-925d-8910daf194e8.png)

**Comment by rossneilson** [comment]
> Sorry, I wasn't clear in the issue.
> 
> In prod, the subgraph info is showing, so this is a config issue somewhere in DAVI that is affecting the develop branch.
> 
> This is a screenshot of a proposal on prod
> 
> ![image](https://user-images.githubusercontent.com/75996796/226330107-73a1be80-3c91-498c-925d-8910daf194e8.png)

ohhh, my bad. 
Should probably add an environment option to bug report templates

**Comment by rossneilson** [comment]
In develop https://project-davi.dev/#/gnosis/0x3f842726188FcD932d43bcA291be28138228e6D9/proposal/0xd0d2b3959f717a877344d81bdd46d5ab60de1105be7b465e807a3b8016c5e46a

I am seeing vote details without issue, could just be localhost
