### ISSUE TITLE
1.5 Scheme selection config clean up

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#330]
Seems we missed a couple of config options in the scheme page. 

Want to add:
- boostedVoteRequiredPercentage
- DAO bounty

![Screenshot 2023-03-23 at 15 26 40](https://user-images.githubusercontent.com/39137239/227121346-785b5cc8-d404-476d-a82f-720bf34fdcbc.jpg)

To make things fit neater we could remove "Can mint reputation" in favour of the "max rep change" which can be 0 if the former is false.

And lets move some items around so the order of the configs goes:
- Type
- Quorum
- boostedVoteRequiredPercentage
- All the time configs
- Can make avatar calls
- Can manage schemes
- Max rep change
- DAO bounty

**Comment by rulfo71** [comment]
@rossneilson here you are diferentiating between `Quorum` and `boostedVoteRequiredPercentage` aren't they the same?

**Comment by rulfo71** [comment]
I'm not sure what you meant by 'All the time configs' but i put all the ones that weren't on the list inside that: 

![image](https://user-images.githubusercontent.com/5303411/227567716-80dca3f9-beba-499c-9ffb-e55bd35f57fc.png)

atm we have two `Quorum` because of the question above

@rossneilson let me know what you think!

**Comment by rossneilson** [comment]
> @rossneilson here you are diferentiating between `Quorum` and `boostedVoteRequiredPercentage` aren't they the same?

They are different actually, quorum is when nothing is boosted and boostedVoteRequiredPercentage is the quorum when boosted, so usually this would be smaller (in current DXdao there is no quorum for boosted proposals)

> I'm not sure what you meant by 'All the time configs' 

My bad for being lazy there, was just meaning to group any of the configs measured in seconds, so:
- Max proposal time
- Proposal time in pre-boost
- Proposal time in boost
- (do we have one for quiet ending period time as well?)
