### ISSUE TITLE
Treasury page

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/davi-monorepo#41]
**User Story**
As a user of DAVI I would like to see the balances of the guild in native currency and tokens in the main guild page or have a section for it.

The guild https://qa.projectdavi.eth.limo/#/gnosis/0xFBcd845E5A4c9e2Cd91b2BB20a92062964C2C391 has 1 xdai and I have no way of knowing it.

**Comment by rossneilson** [comment]
https://www.figma.com/file/EttR9KZTQUrirqMDmI3fQv/DAVI-Dapp-Draft?node-id=365:11575&t=5oPx2lxeoQVFgqxt-0
