### ISSUE TITLE
Handle null ENS avatar

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#7]
With pulen.eth for example returns an avatar URL which does not resolve so we should fallback in this case to the default icon

**Comment by rulfo71** [comment]
just to clarify this is not happening anymore with pulen.eth. It happened because i uploaded an avatar with an error, not sure if it was the format or what

**Comment by Kenny-Gin1** [comment]
@rossneilson  @rulfo71  Is this issue resolved?

**Comment by rulfo71** [comment]
@Kenny-Gin1 i don't think so, I haven't work on it at least

**Comment by rossneilson** [comment]
Not resolved.
You can test with Boris's avatar, seems to be happening there.
https://app.projectdavi.eth.limo/#/gnosis/0x3f842726188FcD932d43bcA291be28138228e6D9/proposal/0xd7924098bc7f547b24c5122beae7e20c5c38f325591a0b0b999a5aa8810f5890

**Comment by dcrescimbeni** [comment]
PR #177
