### ISSUE TITLE
Change module's folder structure

### ISSUE THREAD

**Issue by dcrescimbeni** [DXgovernance/davi-monorepo#77]
The current folder structure has a `common` folder where hooks shared by various governance implementations can be set.

But when we start adding other governance implementations and data sources, this structure can lead to confusion.

@mprasanjith suggested an alternative:

```
modules
    guilds
        common
             fetchers / writers / ...
        SnapshotERC20Guild
             fetchers / writers / ...
        SnapshotRepERC20Guild
        ...
```

The typings and logic will remain unaffected.

**Comment by MiltonTulli** [comment]
I think we should to try to respect the contract name to be consistent. 
`SnapshotERC20Guild` (instead of ERC20SnapshotGuild) , `SnapshotRepERC20Guild` (instead of SnapshotRepGuild), `ERC20Guild` and so on..

**Comment by dcrescimbeni** [comment]
Since all (rpc) hooks are already ported to the store, this seems like a good moment to implement this new structure
