### ISSUE TITLE
Vote view for a proposal & Subgraph fetcher

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/davi-monorepo#8]
**User Story**
As a voter trying to decide how to vote I want to see who has already voted on a proposal and with how much power.

Simplest version would be a modal but perhaps we can find a way to see most high impact votes at a glance?

**Additional context**
Can only be implemented in subgraph supported DAVI

**Comment by borisblock3007** [comment]
Suggesting to use a scrollable module with a list of votes sorted by the amount of REP. Drafts:
![Image](https://user-images.githubusercontent.com/25454493/211283572-ed31170f-3c1e-43b0-bb97-c319addd9d16.png)

Example of the voting page

![Image](https://user-images.githubusercontent.com/25454493/211284194-982c7de6-dc4a-492c-a849-d484e87c462b.png)

**Comment by rossneilson** [comment]
Great work Boris, moving this to next sprint for implementation there

**Comment by rossneilson** [comment]
Also implement subgraph fetcher for this `useProposalVotes()`
